FROM ubuntu:bionic
MAINTAINER Holden Omans <holden.omans@gmail.com>

# Set up static options
ENV DEBIAN_FRONTEND="noninteractive" \
  LANG="en_US.UTF-8" \
  LC_ALL="C.UTF-8" \
  LANGUAGE="en_US.UTF-8"

RUN apt-get -q update && \
  apt-get install -qy git curl python3-pip python3-dev build-essential python3-pil \
    # pillow required libs
    libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev \
    tcl8.6-dev tk8.6-dev python3-tk \
    # misc tools
    wget curl bash fuse unzip && \
  apt-get autoremove -y && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /tmp/*
# Install unrar
ENV RAR_VER "5.7.1"
RUN wget "http://www.rarlab.com/rar/unrarsrc-5.2.6.tar.gz" -O /root/unrarsrc-5.2.6.tar.gz && \
  tar xzf /root/unrarsrc-5.2.6.tar.gz -C /root/

WORKDIR /root/unrar
RUN make && make install && make lib && make install-lib
WORKDIR /
RUN rm -r /root/unrar*
ENV UNRAR_LIB_PATH /usr/lib/libunrar.so

RUN curl https://rclone.org/install.sh | bash

# set version label
ARG MYLAR_COMMIT=v0.3.6
LABEL version ${BASE_VERSION}_${MYLAR_COMMIT}

# It might be better to check out release tags than python3-dev HEAD.
# For development work I reccomend mounting a full git repo from the
# docker host over /app/mylar.
RUN echo "**** install app ****" && \
  git clone https://github.com/mylar3/mylar3.git /app/mylar && \
  cd /app/mylar && \
  git fetch --all --tags && \
  git checkout tags/${MYLAR_COMMIT} -b ${MYLAR_COMMIT}

RUN echo "**** install requirements ****" && \
  pip3 install --no-cache-dir -U -r /app/mylar/requirements.txt && \
  rm -rf ~/.cache/pip/*

RUN groupadd plex --gid 119 && \
  useradd plex -m --gid 119 --uid 113 && \
  passwd -d plex && \
  addgroup root plex && \
  chown -R plex:plex /app/mylar

# Declare volumes needed
VOLUME ["/config","/comics","/downloads"]

# Final setup
# USER plex
EXPOSE 8090
CMD ["python3", "/app/mylar/Mylar.py", "--nolaunch", "--quiet", "--datadir", "/config"]
