FROM ubuntu:16.04
MAINTAINER Holden Omans <holden.omans@gmail.com>

RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8

ENV php_timezone America/New_York
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -yq \
    subversion \
    unrar-free \
    lame \
    software-properties-common \
    mediainfo \
    supervisor \
    ffmpeg \
    mysql-client \
    software-properties-common \
    libmysqlclient-dev \
  && rm -rf /var/lib/apt/lists/*

RUN  add-apt-repository ppa:ondrej/php \
  && add-apt-repository ppa:ondrej/apache2

# install the Pre Reqs and Apache
RUN apt-get update \
  && apt-get -yq install \
    php-pear \
    php-gd \
    php-mysql \
    php-curl \
    apache2 \
  && rm -rf /var/lib/apt/lists/*

# need to add your Newznab plus SVN Password and user here http://newznab4win.blogspot.com.au/2013/01/installing-newznab.html
ARG nn_user
ARG nn_pass
ENV php_timezone America/New_York
ENV path /:/var/www/html/www/

# # add the Config to Apache
# ADD ./newznab.conf /etc/apache2/sites-available/newznab.conf
# RUN mkdir /var/www/newznab/
#
# # pull NNab plus from SVN - Note you need the username and password for Svn Above
# RUN svn co --username $nn_user --password $nn_pass svn://svn.newznab.com/nn/branches/nnplus /var/www/newznab/
#
# RUN chmod 777 /var/www/newznab/www/lib/smarty/templates_c && \
#   chmod 777 /var/www/newznab/www/covers/movies && \
#   chmod 777 /var/www/newznab/www/covers/anime  && \
#   chmod 777 /var/www/newznab/www/covers/music  && \
#   chmod 777 /var/www/newznab/www  && \
#   chmod 777 /var/www/newznab/www/install  && \
#   chmod 777 /var/www/newznab/nzbfiles/
#
# ENV php_mem=4096M
#
# #fix the config files for PHP
# RUN sed -i "s/max_execution_time = 30/max_execution_time = 120/" /etc/php/7.2/cli/php.ini  && \
#   sed -i "s/memory_limit = -1/memory_limit = ${php_mem}/" /etc/php/7.2/cli/php.ini  && \
#   echo "register_globals = Off" >> /etc/php/7.2/cli/php.ini  && \
#   echo "date.timezone =$php_timezone" >> /etc/php/7.2/cli/php.ini  && \
#   sed -i "s/max_execution_time = 30/max_execution_time = 120/" /etc/php/7.2/apache2/php.ini  && \
#   sed -i "s/memory_limit = -1/memory_limit = ${php_mem}/" /etc/php/7.2/apache2/php.ini  && \
#   echo "register_globals = Off" >> /etc/php/7.2/apache2/php.ini  && \
#   echo "date.timezone =$php_timezone" >> /etc/php/7.2/apache2/php.ini  && \
#   sed -i "s/memory_limit = 128M/memory_limit = ${php_mem}/" /etc/php/7.2/apache2/php.ini
#
# ENV APACHE_RUN_DIR /var/run/apache2
#
# # Disable Default site and enable newznab site - Restart Apache here to confirm your newznab.conf is valid in case you changed it
# RUN a2dissite 000-default.conf
# RUN a2ensite newznab
# RUN a2enmod rewrite
# RUN service apache2 restart
#
# # add newznab config file - This needs to be edited
# ADD ./config.php /var/www/newznab/www/config.php
# RUN chmod 777 /var/www/newznab/www/config.php
# RUN mkdir -p /var/www/newznab/www/covers/tv && chmod 777 /var/www/newznab/www/covers/tv
#
# # Add newznab processing script
# ADD ./newznab.sh /newznab.sh
# RUN chmod 755 /*.sh
#
# # Setup supervisor to start Apache and the Newznab scripts to load headers and build releases
# RUN mkdir -p /var/lock/apache2 /var/run/apache2 /var/run/sshd /var/log/supervisor
# COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
#
# RUN a2dismod php7.2 && a2enmod php7.2
#
# # Setup NZB volume this will need to be mapped locally using -v command so that it can persist.
# EXPOSE 80
# VOLUME /nzb
# WORKDIR /var/www/html/www/
# #kickoff Supervisor to start the functions
# CMD ["/usr/bin/supervisord"]
